#!/bin/bash
set -euo pipefail

REPO_DIR="/Users/thor/Sites/wp-core-radar"
LOG_PREFIX="[wp-core-radar]"
PYTHON_BIN="/usr/local/opt/python@3.14/bin/python3.14"

# LaunchAgents run with a minimal PATH. Put the Homebrew Python 3.14 bin
# directory first so child scripts use the same runtime as this wrapper instead
# of macOS' system Python.
export PATH="/usr/local/opt/python@3.14/bin:/usr/local/bin:/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin"
export PYTHON_BIN

cd "$REPO_DIR"

echo "$LOG_PREFIX Starting scheduled radar update at $(date)"
echo "$LOG_PREFIX Using Python: $("$PYTHON_BIN" --version 2>&1)"
echo "$LOG_PREFIX PATH: $PATH"

git pull --rebase origin main

"$PYTHON_BIN" scripts/run-radar.py --continue-on-error

git add data docs reports

if git diff --cached --quiet; then
  echo "$LOG_PREFIX No changes to commit."
  echo "$LOG_PREFIX Finished scheduled radar update at $(date)"
  exit 0
fi

changed_files="$(git diff --cached --name-only)"

if "$PYTHON_BIN" - <<'PY'
from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

files = subprocess.check_output(["git", "diff", "--cached", "--name-only"], text=True).splitlines()

# Files generated by the normal collection pipeline may change only because the
# report/dashboard timestamp changed. Those commits add noise without changing
# the actual radar data or review state.
TIMESTAMP_ONLY_FILES = {
    "docs/radar/index.html",
    "docs/radar/admin-data.json",
    "reports/latest.md",
}

DATED_REPORT_RE = re.compile(r"^reports/radar-\d{4}-\d{2}-\d{2}\.md$")


def normalize(path: str, content: str) -> str:
    if path == "docs/radar/index.html":
        content = re.sub(
            r"Generated \d{4}-\d{2}-\d{2} \d{2}:\d{2}",
            "Generated <timestamp>",
            content,
        )
    elif path == "docs/radar/admin-data.json":
        content = re.sub(
            r'"generated":\s*"[^"]+"',
            '"generated": "<timestamp>"',
            content,
            count=1,
        )
    elif path == "reports/latest.md" or DATED_REPORT_RE.match(path):
        content = re.sub(
            r"Generated:\s*\d{4}-\d{2}-\d{2} \d{2}:\d{2}",
            "Generated: <timestamp>",
            content,
            count=1,
        )
    return content


def head_content(path: str) -> str | None:
    result = subprocess.run(
        ["git", "show", f"HEAD:{path}"],
        text=True,
        capture_output=True,
    )
    if result.returncode != 0:
        return None
    return result.stdout


def worktree_content(path: str) -> str:
    return Path(path).read_text(encoding="utf-8")

for path in files:
    if path not in TIMESTAMP_ONLY_FILES and not DATED_REPORT_RE.match(path):
        sys.exit(1)

    before = head_content(path)
    after = worktree_content(path)

    if before is None or normalize(path, before) != normalize(path, after):
        sys.exit(1)

sys.exit(0)
PY
then
  echo "$LOG_PREFIX Only generated timestamps changed; restoring generated outputs and skipping commit."
  git restore --staged --worktree $changed_files
  echo "$LOG_PREFIX Finished scheduled radar update at $(date)"
  exit 0
fi

git commit -m "Update radar data"

# Review-only dashboard refreshes may be committed by GitHub Actions while this
# longer collection job is running. Rebase immediately before pushing so the
# scheduled collector publishes cleanly instead of failing on a non-fast-forward.
git pull --rebase origin main
git push origin main
echo "$LOG_PREFIX Pushed radar update."

echo "$LOG_PREFIX Finished scheduled radar update at $(date)"
